[Runtime]
verbosity=1

[Debug]
native_xrt_trace=false
device_trace=off
timeline_trace=false

# For embedded profiling prefer device_trace=coarse (fine may overflow buffer).
# device_trace=coarse
# timeline_trace=true
