[Runtime]
verbosity=1

[Debug]
native_xrt_trace=false
device_trace=off
timeline_trace=false

# To enable profiling for a run, set XRT_INI_PATH=/path/to/xrt.ini and uncomment:
# device_trace=fine
# timeline_trace=true
